---
baseURL: https://blog.stephenajulu.com
languageCode: en-us
title: Stephen Ajulu's Blog
pygmentsstyle: monokai
theme: novela
paginate: 17
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
outputs:
  home:
    - "html"
    - "rss"
    - "jsonfeed"
  section:
    - "html"
    - "rss"
    - "jsonfeed"
  taxonomy:
    - "html"
    - "rss"
    - "jsonfeed"
  taxonomyTerm:
    - "html"
    - "rss"
    - "jsonfeed"

outputFormats:
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true

